version:  '3.3'
services:
  dbMysql:
    image: mysql:8.0
    command:  --default-authentication-plugin=mysql_native_password
    environment: 
      MYSQL_ROOT_PASSWORD: L1l1@n3
      MYSQL_DATABASE: exercicios
      MYSQL_USER: acf
      MYSQL_PASSWORD: password
  web:
    image: fpfis/httpd-php:7.4-dev
    working_dir: ${PWD}
    volumes:
      - ${PWD}:${PWD}
      - $HOME/.composer/.auth.json:$HOME/.composer/.auth.json
    environment:
      ASDA_USER:
      ASDA_PASSWORD:
      GITHUB_API_TOKEN:
      GITLAB_API_TOKEN:
      DOCUMENT_ROOT: ${PWD}/web
      XDEBUG_CONFIG: "remote_enable=1 remote_host=10.254.254.254 remote_port=9003 idekey=cloud9ide remote_autostart=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    env_file:
      - .env
    links:
      - dbMysql:db



